# Perfil de acesso do sistema 2 [17258]
Criado pelo gerador 11/11/2019 15:09:45

## Criar perfil de acesso - Customização [17265]
* ST - Criar perfil de acesso - Customização <table:resources/CriarPerfilDeAcessoCustomizacao17265.csv> [17667]
* Clicar no menu de contexto (...) na linha contendo o valor "Criar perfil de acesso - Customização" na tabela
* Clicar no botão Detalhar na listagem
* Verificar os campos da tela <table:resources/CriarPerfilDeAcessoCustomizacao17265.csv> [PerfilDeAcessoDoSistemaPageStep] [17265]
Na tela Detalhar perfil de acesso do sistema o campo Nome deve constar o valor "Criar perfil de acesso - Customização"
Na seção Habilitar funções do sistema no painel Customizacao na categoria Multimídia o checkbox Consultar deve constar o valor "true"
Na seção Habilitar funções do sistema no painel Customizacao na categoria Multimídia o checkbox Alterar deve constar o valor "true"
Na seção Habilitar funções do sistema no painel Customizacao na categoria Multimídia o checkbox Excluir deve constar o valor "true"
Na seção Habilitar funções do sistema no painel Customizacao na categoria Multimídia o checkbox Incluir deve constar o valor "true"
Na seção Habilitar funções do sistema no painel Customizacao na categoria Multimídia o checkbox Aplicar deve constar o valor "true"
Na seção Habilitar funções do sistema no painel Customizacao na categoria Apresentações de Multimídias o checkbox Consultar deve constar o valor "true"
Na seção Habilitar funções do sistema no painel Customizacao na categoria Apresentações de Multimídias o checkbox Alterar deve constar o valor "true"
Na seção Habilitar funções do sistema no painel Customizacao na categoria Apresentações de Multimídias o checkbox Excluir deve constar o valor "true"
Na seção Habilitar funções do sistema no painel Customizacao na categoria Apresentações de Multimídias o checkbox Incluir deve constar o valor "true"
Na seção Habilitar funções do sistema no painel Customizacao na categoria Apresentações de Multimídias o checkbox Aplicar deve constar o valor "true"
* Clicar no botão Voltar

## Criar perfil com acesso a todos as funcionalidades [17274]
* ST - Criar perfil com acesso a todos as funcionalidades <table:resources/CriarPerfilComAcessoATodosAsFuncionalidades17274.csv> [17684]
* Clicar no menu de contexto (...) na linha contendo o valor "Todas as funcionabilidades" na tabela 
* Clicar no botão Detalhar na listagem
* Verificar os campos da tela <table:resources/CriarPerfilComAcessoATodosAsFuncionalidades17274.csv> [PerfilDeAcessoDoSistemaPageStep] [17274]
No campo Nome deve conter o valor "Todas as funcionalidades"
Na seção Habilitar funções do sistema no painel SeloDesconto o checkbox da categoria Consumo selo de desconto deve conter o valor "true"
Na seção Habilitar funções do sistema no painel SeloDesconto o checkbox da categoria Contratos De Integração deve conter o valor "true"
Na seção Habilitar funções do sistema no painel SeloDesconto o checkbox da categoria Pedidos de selo de desconto deve conter o valor "true"
Na seção Habilitar funções do sistema no painel SeloDesconto o checkbox da categoria Produtos de selos de desconto deve conter o valor "true"
Na seção Habilitar funções do sistema no painel SeloDesconto o checkbox da categoria Selos de desconto consumidos deve conter o valor "true"
Na seção Habilitar funções do sistema no painel SeloDesconto o checkbox da categoria Estoque de selos de desconto deve conter o valor "true"
Na seção Habilitar funções do sistema no painel Atendimento assistido o checkbox da categoria Atendimento assistido deve conter o valor "true"
Na seção Habilitar funções do sistema no painel AtendimentoValet o checkbox da categoria AtendimentoValet deve conter o valor "true"
Na seção Habilitar funções do sistema no painel Configurações do estacionamento o checkbox da categoria Bolsões de vagas deve conter o valor "true"
Na seção Habilitar funções do sistema no painel Configurações do estacionamento o checkbox da categoria Arquivos seriais mifare deve conter o valor "true"
Na seção Habilitar funções do sistema no painel Configurações do estacionamento o checkbox da categoria Equipamentos deve conter o valor "true"
Na seção Habilitar funções do sistema no painel Configurações do estacionamento o checkbox da categoria Estacionamentos deve conter o valor "true"
Na seção Habilitar funções do sistema no painel Configurações do estacionamento o checkbox da categoria Grupos de equipamentos deve conter o valor "true"
Na seção Habilitar funções do sistema no painel Configurações do estacionamento o checkbox da categoria Integração com operadora de arrecadação deve conter o valor "true"
Na seção Habilitar funções do sistema no painel Configurações do estacionamento o checkbox da categoria Parâmetros gerais do estacionamento deve conter o valor "true"
Na seção Habilitar funções do sistema no painel Configurações do estacionamento o checkbox da categoria Parâmetros gerais do estacionamento deve conter o valor "true"
Na seção Habilitar funções do sistema no painel Configurações do estacionamento o checkbox da categoria Parâmetros gerais do estacionamento deve conter o valor "true"
Na seção Habilitar funções do sistema no painel Configurações do estacionamento o checkbox da categoria Parâmetros gerais do estacionamento deve conter o valor "true"
Na seção Habilitar funções do sistema no painel Configurações do estacionamento o checkbox da categoria Regras de emissão de bilhetes impressos deve conter o valor "true"
Na seção Habilitar funções do sistema no painel Customização o checkbox da categoria Multimídia deve conter o valor "true"
Na seção Habilitar funções do sistema no painel Customização o checkbox da categoria Apresentações de Multimídias deve conter o valor "true"
Na seção Habilitar funções do sistema no painel Financeiro o checkbox da categoria Emitente fiscal deve conter o valor "true"
Na seção Habilitar funções do sistema no painel Financeiro o checkbox da categoria Configuração de integração TEF deve conter o valor "true"
Na seção Habilitar funções do sistema no painel Financeiro o checkbox da categoria Regras de emissão de recibos deve conter o valor "true"
Na seção Habilitar funções do sistema no painel Financeiro o checkbox da categoria Regras de fechamento dos equipamentos deve conter o valor "true"
Na seção Habilitar funções do sistema no painel Financeiro o checkbox da categoria Regras de numerário de autoatendimento deve conter o valor "true"
Na seção Habilitar funções do sistema no painel Financeiro o checkbox da categoria RegistroCambial deve conter o valor "true"
Na seção Habilitar funções do sistema no painel Instalações e atualizações o checkbox da categoria Agendamento de atualização de aplicativos deve conter o valor "true"
Na seção Habilitar funções do sistema no painel Instalações e atualizações o checkbox da categoria Aplicativos e versões deve conter o valor "true"
Na seção Habilitar funções do sistema no painel Instalações e atualizações o checkbox da categoria Monitoramento de instalações de equipamento deve conter o valor "true"
Na seção Habilitar funções do sistema no painel Operação o checkbox da categoria Agendamento de tarefas automatizadas deve conter o valor "true"
Na seção Habilitar funções do sistema no painel Operação o checkbox da categoria Configurações de modo de contingência deve conter o valor "true"
Na seção Habilitar funções do sistema no painel Operação o checkbox da categoria Alteração temporária do tempo de tolerância deve conter o valor "true"
Na seção Habilitar funções do sistema no painel Operação o checkbox da categoria Clientes do estacionamento deve conter o valor "true"
Na seção Habilitar funções do sistema no painel Operação o checkbox da categoria Contratos de estadia deve conter o valor "true"
Na seção Habilitar funções do sistema no painel Operação o checkbox da categoria Controle de equipamentos deve conter o valor "true"
Na seção Habilitar funções do sistema no painel Operação o checkbox da categoria Estadias Abertas deve conter o valor "true"
Na seção Habilitar funções do sistema no painel Operação o checkbox da categoria Regras de limpeza de pátio automática deve conter o valor "true"
Na seção Habilitar funções do sistema no painel Operação o checkbox da categoria Midias perdidas pré autorizadas deve conter o valor "true"
Na seção Habilitar funções do sistema no painel Operação o checkbox da categoria Operação de múltiplas cancelas deve conter o valor "true"
Na seção Habilitar funções do sistema no painel Operação o checkbox da categoria Tipos de ocorrências nas estadia deve conter o valor "true"
Na seção Habilitar funções do sistema no painel Operação o checkbox da categoria Usuários não autorizados deve conter o valor "true"
Na seção Habilitar funções do sistema no painel Operação o checkbox da categoria CapturasLPR deve conter o valor "true"
Na seção Habilitar funções do sistema no painel Operação o checkbox da categoria Analisar midia de operação deve conter o valor "true"
Na seção Habilitar funções do sistema no painel Produtos de estadia o checkbox da categoria Estruturas de tabelas de cobrança deve conter o valor "true"
Na seção Habilitar funções do sistema no painel Produtos de estadia o checkbox da categoria Produtos de estadia deve conter o valor "true"
Na seção Habilitar funções do sistema no painel Produtos de estadia o checkbox da categoria Regras de acesso deve conter o valor "true"
Na seção Habilitar funções do sistema no painel Produtos de estadia o checkbox da categoria Regras de cobrança deve conter o valor "true"
Na seção Habilitar funções do sistema no painel Produtos de estadia o checkbox da categoria Regras de descontos deve conter o valor "true"
Na seção Habilitar funções do sistema no painel Produtos de estadia o checkbox da categoria Regras de mídia perdida deve conter o valor "true"
Na seção Habilitar funções do sistema no painel Produtos de estadia o checkbox da categoria Tabelas de cobrança deve conter o valor "true"
Na seção Habilitar funções do sistema no painel Produtos de estadia o checkbox da categoria Tipos de desconto deve conter o valor "true"
Na seção Habilitar funções do sistema no painel Relatórios padrão o checkbox da categoria Documentos fiscais deve conter o valor "true"
Na seção Habilitar funções do sistema no painel Relatórios padrão o checkbox da categoria Estadias deve conter o valor "true"
Na seção Habilitar funções do sistema no painel Relatórios padrão o checkbox da categoria Eventos de estadia deve conter o valor "true"
Na seção Habilitar funções do sistema no painel Relatórios padrão o checkbox da categoria Eventos de sistema deve conter o valor "true"
Na seção Habilitar funções do sistema no painel Relatórios padrão o checkbox da categoria Fechamento geral deve conter o valor "true"
Na seção Habilitar funções do sistema no painel Relatórios padrão o checkbox da categoria Fluxo por período deve conter o valor "true"
Na seção Habilitar funções do sistema no painel Relatórios padrão o checkbox da categoria Isenções deve conter o valor "true"
Na seção Habilitar funções do sistema no painel Relatórios padrão o checkbox da categoria Log de auditoria deve conter o valor "true"
Na seção Habilitar funções do sistema no painel Relatórios padrão o checkbox da categoria Log numerário autoatendimento deve conter o valor "true"
Na seção Habilitar funções do sistema no painel Relatórios padrão o checkbox da categoria Permanência deve conter o valor "true"
Na seção Habilitar funções do sistema no painel Relatórios padrão o checkbox da categoria Receita tipo de produto estadia deve conter o valor "true"
Na seção Habilitar funções do sistema no painel Segurança o checkbox da categoria Licenças de uso deve conter o valor "true"
Na seção Habilitar funções do sistema no painel Segurança o checkbox da categoria Perfis de acesso do sistema deve conter o valor "true"
Na seção Habilitar funções do sistema no painel Segurança o checkbox da categoria Usuários do sistema deve conter o valor "true"
Na seção Habilitar funções do sistema no painel Relatórios customizados o checkbox da categoria Comum deve conter o valor "true"
* Clicar no botão Voltar

