# Perfil de acesso do sistema 2 [17258]
Criado pelo gerador 11/11/2019 15:09:45

## Criar perfil com acesso a Produtos de estadia [17270]
* ST - Criar perfil com acesso a Produtos de estadia <table:resources/CriarPerfilComAcessoAProdutosDeEstadia17270.csv> [17683]
* Clicar no menu de contexto (...) na linha contendo o valor "Produtos de estadia" na tabela 
* Clicar no botão Detalhar na listagem
* Verificar os campos da tela <table:resources/CriarPerfilComAcessoAProdutosDeEstadia17270.csv> [PerfilDeAcessoDoSistemaPageStep] [17270]
Na tela Detalhar perfil de acesso do sistema o campo Nome deve constar o valor "Produtos de estadia"
Na seção Habilitar funções do sistema no painel Produtos de estadia na categoria Estruturas de tabelas de cobrança o checkbox Consultar deve conter o valor "true"
Na seção Habilitar funções do sistema no painel Produtos de estadia na categoria Estruturas de tabelas de cobrança o checkbox Incluir deve conter o valor "true"
Na seção Habilitar funções do sistema no painel Produtos de estadia na categoria Estruturas de tabelas de cobrança o checkbox Alterar deve conter o valor "true"
Na seção Habilitar funções do sistema no painel Produtos de estadia na categoria Estruturas de tabelas de cobrança o checkbox Excluir deve conter o valor "true"
Na seção Habilitar funções do sistema no painel Produtos de estadia na categoria Produtos de estadia o checkbox Consultar deve conter o valor "true"
Na seção Habilitar funções do sistema no painel Produtos de estadia na categoria Produtos de estadia o checkbox Incluir deve conter o valor "true"
Na seção Habilitar funções do sistema no painel Produtos de estadia na categoria Produtos de estadia o checkbox Alterar deve conter o valor "true"
Na seção Habilitar funções do sistema no painel Produtos de estadia na categoria Produtos de estadia o checkbox Excluir deve conter o valor "true"
Na seção Habilitar funções do sistema no painel Produtos de estadia na categoria Produtos de estadia o checkbox Consultar deve conter o valor "true"
Na seção Habilitar funções do sistema no painel Produtos de estadia na categoria Regras de acesso o checkbox Consultar deve conter o valor "true"
Na seção Habilitar funções do sistema no painel Produtos de estadia na categoria Regras de acesso o checkbox Incluir deve conter o valor "true"
Na seção Habilitar funções do sistema no painel Produtos de estadia na categoria Regras de acesso o checkbox Alterar deve conter o valor "true"
Na seção Habilitar funções do sistema no painel Produtos de estadia na categoria Regras de acesso o checkbox Excluir deve conter o valor "true"
Na seção Habilitar funções do sistema no painel Produtos de estadia na categoria Regras de cobrança o checkbox Consultar deve conter o valor "true"
Na seção Habilitar funções do sistema no painel Produtos de estadia na categoria Regras de cobrança o checkbox Incluir deve conter o valor "true"
Na seção Habilitar funções do sistema no painel Produtos de estadia na categoria Regras de cobrança o checkbox Alterar deve conter o valor "true"
Na seção Habilitar funções do sistema no painel Produtos de estadia na categoria Regras de cobrança o checkbox Excluir deve conter o valor "true"
Na seção Habilitar funções do sistema no painel Produtos de estadia na categoria Regras de cobrança o checkbox Aplicar deve conter o valor "true"
Na seção Habilitar funções do sistema no painel Produtos de estadia na categoria Regras de Descontos o checkbox Consultar deve conter o valor "true"
Na seção Habilitar funções do sistema no painel Produtos de estadia na categoria Regras de Descontos o checkbox Incluir deve conter o valor "true"
Na seção Habilitar funções do sistema no painel Produtos de estadia na categoria Regras de Descontos o checkbox Alterar deve conter o valor "true"
Na seção Habilitar funções do sistema no painel Produtos de estadia na categoria Regras de Descontos o checkbox Excluir deve conter o valor "true"
Na seção Habilitar funções do sistema no painel Produtos de estadia na categoria Regras de Descontos o checkbox Aplicar deve conter o valor "true"
Na seção Habilitar funções do sistema no painel Produtos de estadia na categoria Regras de mídia perdida o checkbox Consultar deve conter o valor "true"
Na seção Habilitar funções do sistema no painel Produtos de estadia na categoria Regras de mídia perdida o checkbox Incluir deve conter o valor "true"
Na seção Habilitar funções do sistema no painel Produtos de estadia na categoria Regras de mídia perdida o checkbox Alterar deve conter o valor "true"
Na seção Habilitar funções do sistema no painel Produtos de estadia na categoria Regras de mídia perdida o checkbox Excluir deve conter o valor "true"
Na seção Habilitar funções do sistema no painel Produtos de estadia na categoria Regras de mídia perdida o checkbox Aplicar deve conter o valor "true"
Na seção Habilitar funções do sistema no painel Produtos de estadia na categoria Tabelas de cobrança o checkbox Consultar deve conter o valor "true"
Na seção Habilitar funções do sistema no painel Produtos de estadia na categoria Tabelas de cobrança o checkbox Incluir deve conter o valor "true"
Na seção Habilitar funções do sistema no painel Produtos de estadia na categoria Tabelas de cobrança o checkbox Alterar deve conter o valor "true"
Na seção Habilitar funções do sistema no painel Produtos de estadia na categoria Tabelas de cobrança o checkbox Excluir deve conter o valor "true"
Na seção Habilitar funções do sistema no painel Produtos de estadia na categoria Tipos de desconto o checkbox Consultar deve conter o valor "true"
Na seção Habilitar funções do sistema no painel Produtos de estadia na categoria Tipos de desconto o checkbox Alterar deve conter o valor "true"
* Clicar no botão Voltar

## Criar perfil de acesso - Operação [17269]
* ST - Criar perfil de acesso - Operação <table:resources/CriarPerfilDeAcessoOperacao17269.csv> [17610]
* Clicar no menu de contexto (...) na linha contendo o valor "perfil de acesso - Operação" na tabela
* Clicar no botão Detalhar na listagem
* Verificar os campos da tela <table:resources/CriarPerfilDeAcessoOperacao17269.csv> [PerfilDeAcessoDoSistemaPageStep] [17269]
Na tela Detalhar perfil de acesso do sistema o campo Nome deve constar o valor "perfil de acesso - Operação"
Na seção Habilitar funções do sistema no painel Operacao na categoria Agendamento de tarefas automatizadas o checkbox Consultar deve constar o valor "true"
Na seção Habilitar funções do sistema no painel Operacao na categoria Agendamento de tarefas automatizadas o checkbox Incluir deve constar o valor "true"
Na seção Habilitar funções do sistema no painel Operacao na categoria Agendamento de tarefas automatizadas o checkbox Alterar deve constar o valor "true"
Na seção Habilitar funções do sistema no painel Operacao na categoria Agendamento de tarefas automatizadas o checkbox Excluir deve constar o valor "true"
Na seção Habilitar funções do sistema no painel Operacao na categoria Configuração de modo de contingência o checkbox Consultar deve constar o valor "true"
Na seção Habilitar funções do sistema no painel Operacao na categoria Configuração de modo de contingência o checkbox Incluir deve constar o valor "true"
Na seção Habilitar funções do sistema no painel Operacao na categoria Alteração temporária do tempo de tolerância o checkbox Consultar deve constar o valor "true"
Na seção Habilitar funções do sistema no painel Operacao na categoria Alteração temporária do tempo de tolerância o checkbox Incluir deve constar o valor "true"
Na seção Habilitar funções do sistema no painel Operacao na categoria Clientes do estacionamento o checkbox Consultar deve constar o valor "true"
Na seção Habilitar funções do sistema no painel Operacao na categoria Clientes do estacionamento o checkbox Incluir deve constar o valor "true"
Na seção Habilitar funções do sistema no painel Operacao na categoria Clientes do estacionamento o checkbox Alterar deve constar o valor "true"
Na seção Habilitar funções do sistema no painel Operacao na categoria Clientes do estacionamento o checkbox Excluir deve constar o valor "true"
Na seção Habilitar funções do sistema no painel Operacao na categoria Contratos de estadia o checkbox Consultar deve constar o valor "true"
Na seção Habilitar funções do sistema no painel Operacao na categoria Contratos de estadia o checkbox Incluir deve constar o valor "true"
Na seção Habilitar funções do sistema no painel Operacao na categoria Contratos de estadia o checkbox Alterar deve constar o valor "true"
Na seção Habilitar funções do sistema no painel Operacao na categoria Contratos de estadia o checkbox Excluir deve constar o valor "true"
Na seção Habilitar funções do sistema no painel Operacao na categoria Controle de equipamentos o checkbox Consultar deve constar o valor "true"
Na seção Habilitar funções do sistema no painel Operacao na categoria Controle de equipamentos o checkbox Ações de cancela deve constar o valor "true"
Na seção Habilitar funções do sistema no painel Operacao na categoria Controle de equipamentos o checkbox Comandos auxiliares deve constar o valor "true"
Na seção Habilitar funções do sistema no painel Operacao na categoria Controle de equipamentos o checkbox Entrada manual deve constar o valor "true"
Na seção Habilitar funções do sistema no painel Operacao na categoria Controle de equipamentos o checkbox AssociarMidiaPerdida deve constar o valor "true"
Na seção Habilitar funções do sistema no painel Operacao na categoria Controle de equipamentos o checkbox Saída manual deve constar o valor "true"
Na seção Habilitar funções do sistema no painel Operacao na categoria Controle de equipamentos o checkbox Passagem manual deve constar o valor "true"
Na seção Habilitar funções do sistema no painel Operacao na categoria Estadias abertas o checkbox Consultar deve constar o valor "true"
Na seção Habilitar funções do sistema no painel Operacao na categoria Regras de limpeza de pátio automática o checkbox Consultar deve constar o valor "true"
Na seção Habilitar funções do sistema no painel Operacao na categoria Regras de limpeza de pátio automática o checkbox Incluir deve constar o valor "true"
Na seção Habilitar funções do sistema no painel Operacao na categoria Regras de limpeza de pátio automática o checkbox Alterar deve constar o valor "true"
Na seção Habilitar funções do sistema no painel Operacao na categoria Regras de limpeza de pátio automática o checkbox Excluir deve constar o valor "true"
Na seção Habilitar funções do sistema no painel Operacao na categoria Mídias perdidas pré autorizadas o checkbox Consultar deve constar o valor "true"
Na seção Habilitar funções do sistema no painel Operacao na categoria Operação de múltiplas cancelas o checkbox Consultar deve constar o valor "true"
Na seção Habilitar funções do sistema no painel Operacao na categoria Tipos de ocorrências nas estadia o checkbox Consultar deve constar o valor "true"
Na seção Habilitar funções do sistema no painel Operacao na categoria Tipos de ocorrências nas estadia o checkbox Incluir deve constar o valor "true"
Na seção Habilitar funções do sistema no painel Operacao na categoria Tipos de ocorrências nas estadia o checkbox Alterar deve constar o valor "true"
Na seção Habilitar funções do sistema no painel Operacao na categoria Tipos de ocorrências nas estadia o checkbox Excluir deve constar o valor "true"
Na seção Habilitar funções do sistema no painel Operacao na categoria Usuários não autorizados o checkbox Consultar deve constar o valor "true"
Na seção Habilitar funções do sistema no painel Operacao na categoria Usuários não autorizados o checkbox Incluir deve constar o valor "true"
Na seção Habilitar funções do sistema no painel Operacao na categoria Usuários não autorizados o checkbox Alterar deve constar o valor "true"
Na seção Habilitar funções do sistema no painel Operacao na categoria Usuários não autorizados o checkbox Excluir deve constar o valor "true"
Na seção Habilitar funções do sistema no painel Operacao na categoria CapturasLPR o checkbox Consultar deve constar o valor "true"
Na seção Habilitar funções do sistema no painel Operacao na categoria CapturasLPR o checkbox Alterar deve constar o valor "true"
Na seção Habilitar funções do sistema no painel Operacao na categoria Analisar mídia de operação o checkbox Consultar deve constar o valor "true"
* Clicar no botão Voltar