# Perfil de acesso do sistema 2 [17258]
Criado pelo gerador 11/11/2019 15:09:45

## Alterar um perfil de acesso com todas as funcionalidades [17275]
* ST - Criar perfil com acesso a todos as funcionalidades <table:resources/AlterarUmPerfilDeAcessoComTodasAsFuncionalidades17275.csv> [17684]
* Clicar no menu de contexto (...) na linha contendo o valor "Todas as funcionabilidades para alterar" na tabela
* Clicar no botão Alterar na listagem
* Preencher os campos da tela <table:resources/AlterarUmPerfilDeAcessoComTodasAsFuncionalidades17275.csv> [PerfilDeAcessoDoSistemaPageStep] [17275]
No campo Nome alterar o valor para "Tudo alterado"
Na seção Habilitar funções do sistema no painel SeloDesconto desmarcar o checkbox da categoria Consumo selo de desconto com o valor "false"
Na seção Habilitar funções do sistema no painel SeloDesconto desmarcar o checkbox da categoria Contratos De Integração com o valor "false"
Na seção Habilitar funções do sistema no painel SeloDesconto desmarcar o checkbox da categoria Pedidos de selo de desconto com o valor "false"
Na seção Habilitar funções do sistema no painel SeloDesconto desmarcar o checkbox da categoria Produtos de selos de desconto com o valor "false"
Na seção Habilitar funções do sistema no painel SeloDesconto desmarcar o checkbox da categoria Selos de desconto consumidos com o valor "false"
Na seção Habilitar funções do sistema no painel SeloDesconto desmarcar o checkbox da categoria Estoque de selos de desconto com o valor "false"
Na seção Habilitar funções do sistema no painel Atendimento assistido desmarcar o checkbox da categoria Atendimento assistido com o valor "false"
Na seção Habilitar funções do sistema no painel AtendimentoValet desmarcar o checkbox da categoria AtendimentoValet com o valor "false"
Na seção Habilitar funções do sistema no painel Configurações do estacionamento desmarcar o checkbox da categoria Bolsões de vagas com o valor "false"
Na seção Habilitar funções do sistema no painel Configurações do estacionamento desmarcar o checkbox da categoria Arquivos seriais mifare com o valor "false"
Na seção Habilitar funções do sistema no painel Configurações do estacionamento desmarcar o checkbox da categoria Equipamentos com o valor "false"
Na seção Habilitar funções do sistema no painel Configurações do estacionamento desmarcar o checkbox da categoria Estacionamentos com o valor "false"
Na seção Habilitar funções do sistema no painel Configurações do estacionamento desmarcar o checkbox da categoria Grupos de equipamentos com o valor "false"
Na seção Habilitar funções do sistema no painel Configurações do estacionamento desmarcar o checkbox da categoria Integração com operadora de arrecadação com o valor "false"
Na seção Habilitar funções do sistema no painel Configurações do estacionamento desmarcar o checkbox da categoria Parâmetros gerais do estacionamento com o valor "false"
Na seção Habilitar funções do sistema no painel Configurações do estacionamento desmarcar o checkbox da categoria Regras de emissão de bilhetes impressos com o valor "false"
Na seção Habilitar funções do sistema no painel Customização desmarcar o checkbox da categoria Configuração de mensagem de áudio com o valor "false"
Na seção Habilitar funções do sistema no painel Customização desmarcar o checkbox da categoria Configuração da tela de VGA com o valor "false"
Na seção Habilitar funções do sistema no painel Financeiro desmarcar o checkbox da categoria Emitente fiscal com o valor "false"
Na seção Habilitar funções do sistema no painel Financeiro desmarcar o checkbox da categoria Configuração de integração TEF com o valor "false"
Na seção Habilitar funções do sistema no painel Financeiro desmarcar o checkbox da categoria Regras de emissão de recibos com o valor "false"
Na seção Habilitar funções do sistema no painel Financeiro desmarcar o checkbox da categoria Regras de fechamento dos equipamentos com o valor "false"
Na seção Habilitar funções do sistema no painel Financeiro desmarcar o checkbox da categoria Regras de numerário de autoatendimento com o valor "false"
Na seção Habilitar funções do sistema no painel Financeiro desmarcar o checkbox da categoria RegistroCambial com o valor "false"
Na seção Habilitar funções do sistema no painel Instalações e atualizações desmarcar o checkbox da categoria Agendamento de atualização de aplicativos com o valor "false"
Na seção Habilitar funções do sistema no painel Instalações e atualizações desmarcar o checkbox da categoria Aplicativos e versões com o valor "false"
Na seção Habilitar funções do sistema no painel Instalações e atualizações desmarcar o checkbox da categoria Monitoramento de instalações de equipamento com o valor "false"
Na seção Habilitar funções do sistema no painel Operação desmarcar o checkbox da categoria Agendamento de tarefas automatizadas com o valor "false"
Na seção Habilitar funções do sistema no painel Operação desmarcar o checkbox da categoria Configurações de modo de contingência com o valor "false"
Na seção Habilitar funções do sistema no painel Operação desmarcar o checkbox da categoria Alteração temporária do tempo de tolerância com o valor "false"
Na seção Habilitar funções do sistema no painel Operação desmarcar o checkbox da categoria Clientes do estacionamento com o valor "false"
Na seção Habilitar funções do sistema no painel Operação desmarcar o checkbox da categoria Contratos de estadia com o valor "false"
Na seção Habilitar funções do sistema no painel Operação desmarcar o checkbox da categoria Controle de equipamentos com o valor "false"
Na seção Habilitar funções do sistema no painel Operação desmarcar o checkbox da categoria Estadias Abertas com o valor "false"
Na seção Habilitar funções do sistema no painel Operação desmarcar o checkbox da categoria Regras de limpeza de pátio automática com o valor "false"
Na seção Habilitar funções do sistema no painel Operação desmarcar o checkbox da categoria Midias perdidas pré autorizadas com o valor "false"
Na seção Habilitar funções do sistema no painel Operação desmarcar o checkbox da categoria Operação de múltiplas cancelas com o valor "false"
Na seção Habilitar funções do sistema no painel Operação desmarcar o checkbox da categoria Tipos de ocorrências nas estadia com o valor "false"
Na seção Habilitar funções do sistema no painel Operação desmarcar o checkbox da categoria Usuários não autorizados com o valor "false"
Na seção Habilitar funções do sistema no painel Operação desmarcar o checkbox da categoria CapturasLPR com o valor "false"
Na seção Habilitar funções do sistema no painel Operação desmarcar o checkbox da categoria Analisar midia de operação com o valor "false"
Na seção Habilitar funções do sistema no painel Produtos de estadia desmarcar o checkbox da categoria Estruturas de tabelas de cobrança com o valor "false"
Na seção Habilitar funções do sistema no painel Produtos de estadia desmarcar o checkbox da categoria Produtos de estadia com o valor "false"
Na seção Habilitar funções do sistema no painel Produtos de estadia desmarcar o checkbox da categoria Regras de acesso com o valor "false"
Na seção Habilitar funções do sistema no painel Produtos de estadia desmarcar o checkbox da categoria Regras de cobrança com o valor "false"
Na seção Habilitar funções do sistema no painel Produtos de estadia desmarcar o checkbox da categoria Regras de descontos com o valor "false"
Na seção Habilitar funções do sistema no painel Produtos de estadia desmarcar o checkbox da categoria Regras de mídia perdida com o valor "false"
Na seção Habilitar funções do sistema no painel Produtos de estadia desmarcar o checkbox da categoria Tabelas de cobrança com o valor "false"
Na seção Habilitar funções do sistema no painel Produtos de estadia desmarcar o checkbox da categoria Tipos de desconto com o valor "false"
Na seção Habilitar funções do sistema no painel Relatórios padrão desmarcar o checkbox da categoria Documentos fiscais com o valor "false"
Na seção Habilitar funções do sistema no painel Relatórios padrão desmarcar o checkbox da categoria Estadias com o valor "false"
Na seção Habilitar funções do sistema no painel Relatórios padrão desmarcar o checkbox da categoria Eventos de estadia com o valor "false"
Na seção Habilitar funções do sistema no painel Relatórios padrão desmarcar o checkbox da categoria Eventos de sistema com o valor "false"
Na seção Habilitar funções do sistema no painel Relatórios padrão desmarcar o checkbox da categoria Fechamento geral com o valor "false"
Na seção Habilitar funções do sistema no painel Relatórios padrão desmarcar o checkbox da categoria Fluxo por período com o valor "false"
Na seção Habilitar funções do sistema no painel Relatórios padrão desmarcar o checkbox da categoria Isenções com o valor "false"
Na seção Habilitar funções do sistema no painel Relatórios padrão desmarcar o checkbox da categoria Log de auditoria com o valor "false"
Na seção Habilitar funções do sistema no painel Relatórios padrão desmarcar o checkbox da categoria Log numerário autoatendimento com o valor "false"
Na seção Habilitar funções do sistema no painel Relatórios padrão desmarcar o checkbox da categoria Receita tipo de produto estadia com o valor "false"
Na seção Habilitar funções do sistema no painel Segurança desmarcar o checkbox da categoria Licenças de uso com o valor "false"
Na seção Habilitar funções do sistema no painel Segurança desmarcar o checkbox da categoria Perfis de acesso do sistema com o valor "false"
Na seção Habilitar funções do sistema no painel Segurança desmarcar o checkbox da categoria Usuários do sistema com o valor "false"
Na seção Habilitar funções do sistema no painel Relatórios customizados desmarcar o checkbox da categoria Comum com o valor "false"
* Clicar no botão Salvar
* Clicar no menu de contexto (...) na linha contendo o valor "Tudo alterado" na tabela
* Clicar no botão Detalhar na listagem
* Verificar os campos da tela <table:resources/AlterarUmPerfilDeAcessoComTodasAsFuncionalidades17275.csv> [PerfilDeAcessoDoSistemaPageStep] [17275]
No campo Nome deve constar o valor "Tudo alterado"
Na seção Habilitar funções do sistema no painel SeloDesconto o checkbox da categoria Consumo selo de desconto deve constar o valor "false"
Na seção Habilitar funções do sistema no painel SeloDesconto o checkbox da categoria Contratos De Integração deve constar o valor "false"
Na seção Habilitar funções do sistema no painel SeloDesconto o checkbox da categoria Pedidos de selo de desconto deve constar o valor "false"
Na seção Habilitar funções do sistema no painel SeloDesconto o checkbox da categoria Produtos de selos de desconto deve constar o valor "false"
Na seção Habilitar funções do sistema no painel SeloDesconto o checkbox da categoria Selos de desconto consumidos deve constar o valor "false"
Na seção Habilitar funções do sistema no painel SeloDesconto o checkbox da categoria Estoque de selos de desconto deve constar o valor "false"
Na seção Habilitar funções do sistema no painel Atendimento assistido o checkbox da categoria Atendimento assistido deve conter o valor "false"
Na seção Habilitar funções do sistema no painel Configurações do estacionamento o checkbox da categoria Bolsões de vagas deve constar o valor "false"
Na seção Habilitar funções do sistema no painel Configurações do estacionamento o checkbox da categoria Arquivos seriais mifare deve constar o valor "false"
Na seção Habilitar funções do sistema no painel Configurações do estacionamento o checkbox da categoria Equipamentos deve constar o valor "false"
Na seção Habilitar funções do sistema no painel Configurações do estacionamento o checkbox da categoria Estacionamentos deve constar o valor "false"
Na seção Habilitar funções do sistema no painel Configurações do estacionamento o checkbox da categoria Grupos de equipamentos deve constar o valor "false"
Na seção Habilitar funções do sistema no painel Configurações do estacionamento o checkbox da categoria Integração com operadora de arrecadação deve constar o valor "false"
Na seção Habilitar funções do sistema no painel Configurações do estacionamento o checkbox da categoria Parâmetros gerais do estacionamento deve constar o valor "false"
Na seção Habilitar funções do sistema no painel Configurações do estacionamento o checkbox da categoria Regras de emissão de bilhetes impressos deve constar o valor "false"
Na seção Habilitar funções do sistema no painel Customização o checkbox da categoria Configuração de mensagem de áudio deve constar o valor "false"
Na seção Habilitar funções do sistema no painel Customização o checkbox da categoria Configuração da tela de VGA deve constar o valor "false"
Na seção Habilitar funções do sistema no painel Financeiro o checkbox da categoria Emitente fiscal deve constar o valor "false"
Na seção Habilitar funções do sistema no painel Financeiro o checkbox da categoria Configuração de integração TEF deve constar o valor "false"
Na seção Habilitar funções do sistema no painel Financeiro o checkbox da categoria Regras de emissão de recibos deve constar o valor "false"
Na seção Habilitar funções do sistema no painel Financeiro o checkbox da categoria Regras de fechamento dos equipamentos deve conter o valor "false"
Na seção Habilitar funções do sistema no painel Financeiro o checkbox da categoria RegistroCambial deve constar o valor "false"
Na seção Habilitar funções do sistema no painel Instalações e atualizações o checkbox da categoria Agendamento de atualização de aplicativos deve constar o valor "false"
Na seção Habilitar funções do sistema no painel Instalações e atualizações o checkbox da categoria Aplicativos e versões deve constar o valor "false"
Na seção Habilitar funções do sistema no painel Instalações e atualizações o checkbox da categoria Monitoramento de instalações de equipamento deve constar o valor "false"
Na seção Habilitar funções do sistema no painel Operação o checkbox da categoria Agendamento de tarefas automatizadas deve constar o valor "false"
Na seção Habilitar funções do sistema no painel Operação o checkbox da categoria Configurações de modo de contingência deve constar o valor "false"
Na seção Habilitar funções do sistema no painel Operação o checkbox da categoria Alteração temporária do tempo de tolerância deve constar o valor "false"
Na seção Habilitar funções do sistema no painel Operação o checkbox da categoria Clientes do estacionamento deve constar o valor "false"
Na seção Habilitar funções do sistema no painel Operação o checkbox da categoria Contratos de estadia deve constar o valor "false"
Na seção Habilitar funções do sistema no painel Operação o checkbox da categoria Controle de equipamentos deve constar o valor "false"
Na seção Habilitar funções do sistema no painel Operação o checkbox da categoria Estadias Abertas deve constar o valor "false"
Na seção Habilitar funções do sistema no painel Operação o checkbox da categoria Regras de limpeza de pátio automática deve constar o valor "false"
Na seção Habilitar funções do sistema no painel Operação o checkbox da categoria Midias perdidas pré autorizadas deve constar o valor "false"
Na seção Habilitar funções do sistema no painel Operação o checkbox da categoria Operação de múltiplas cancelas deve constar o valor "false"
Na seção Habilitar funções do sistema no painel Operação o checkbox da categoria Tipos de ocorrências nas estadia deve constar o valor "false"
Na seção Habilitar funções do sistema no painel Operação o checkbox da categoria Usuários não autorizados deve constar o valor "false"
Na seção Habilitar funções do sistema no painel Operação o checkbox da categoria CapturasLPR deve constar o valor "false"
Na seção Habilitar funções do sistema no painel Operação o checkbox da categoria Analisar midia de operação deve constar o valor "false"
Na seção Habilitar funções do sistema no painel Produtos de estadia o checkbox da categoria Estruturas de tabelas de cobrança deve constar o valor "false"
Na seção Habilitar funções do sistema no painel Produtos de estadia o checkbox da categoria Produtos de estadia deve constar o valor "false"
Na seção Habilitar funções do sistema no painel Produtos de estadia o checkbox da categoria Regras de acesso deve constar o valor "false"
Na seção Habilitar funções do sistema no painel Produtos de estadia o checkbox da categoria Regras de cobrança deve constar o valor "false"
Na seção Habilitar funções do sistema no painel Produtos de estadia o checkbox da categoria Regras de descontos deve constar o valor "false"
Na seção Habilitar funções do sistema no painel Produtos de estadia o checkbox da categoria Regras de mídia perdida deve constar o valor "false"
Na seção Habilitar funções do sistema no painel Produtos de estadia o checkbox da categoria Tabelas de cobrança deve constar o valor "false"
Na seção Habilitar funções do sistema no painel Produtos de estadia o checkbox da categoria Tipos de desconto deve constar o valor "false"
Na seção Habilitar funções do sistema no painel Relatórios padrão o checkbox da categoria Documentos fiscais deve constar o valor "false"
Na seção Habilitar funções do sistema no painel Relatórios padrão o checkbox da categoria Estadias deve constar o valor "false"
Na seção Habilitar funções do sistema no painel Relatórios padrão o checkbox da categoria Eventos de estadia deve constar o valor "false"
Na seção Habilitar funções do sistema no painel Relatórios padrão o checkbox da categoria Eventos de sistema deve constar o valor "false"
Na seção Habilitar funções do sistema no painel Relatórios padrão o checkbox da categoria Fechamento geral deve constar o valor "false"
Na seção Habilitar funções do sistema no painel Relatórios padrão o checkbox da categoria Fluxo por período deve constar o valor "false"
Na seção Habilitar funções do sistema no painel Relatórios padrão o checkbox da categoria Isenções deve constar o valor "false"
Na seção Habilitar funções do sistema no painel Relatórios padrão o checkbox da categoria Log de auditoria deve constar o valor "false"
Na seção Habilitar funções do sistema no painel Relatórios padrão o checkbox da categoria Log numerário autoatendimento deve constar o valor "false"
Na seção Habilitar funções do sistema no painel Relatórios padrão o checkbox da categoria Permanência deve constar o valor "false"
Na seção Habilitar funções do sistema no painel Relatórios padrão o checkbox da categoria Receita tipo de produto estadia deve constar o valor "false"
Na seção Habilitar funções do sistema no painel Segurança o checkbox da categoria Licenças de uso deve constar o valor "false"
Na seção Habilitar funções do sistema no painel Segurança o checkbox da categoria Usuários do sistema deve constar o valor "false"
Na seção Habilitar funções do sistema no painel Relatórios customizados o checkbox da categoria Comum deve constar o valor "false"
* Clicar no botão Voltar

